# Generated by Django 3.0.5 on 2020-05-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='result',
            new_name='output',
        ),
    ]
