# Generated by Django 3.0.5 on 2020-05-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200502_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
