# Generated by Django 3.0.5 on 2020-05-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_job_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='output',
            field=models.TextField(default=''),
        ),
    ]
